name: Update Stock Reporter

on:
  workflow_dispatch:
    inputs:
      stock:
        description: 'Stock symbol'
        required: true
      channel:
        description: 'Source channel'
        required: true
      reporter:
        description: 'Reporter name'
        required: true

jobs:
  update_stock_reporters:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      id: checkout
      uses: actions/checkout@v3
    - name: Setup gitrows
      run: npm i gitrows
    - name: Update stock reporters
      run: |
        const gitrows = require('gitrows')
        const data = {
          key: inputs.stock,
          channel: inputs.channel,
          reporter: inputs.reporter
        }
        gitrows.put('stock_dashboard_data.json', data)
        .then((response) => {
          console.log(response)
        })
        .catch((error) => {
          console.log(error)
        })
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add stock_dashboard_data.json
        git commit -m "Add reporter $reporter to stock $stock"
        git push
