name: Update Stock Reporters

on:
  workflow_dispatch:
    inputs:
      stock_symbol:
        description: 'Enter the stock symbol (e.g. TSLA, NNDM, ARKK)'
        required: true
      channel:
        description: 'Enter the name of the channel (e.g. youtube, twitter, yahooFinance)'
        required: true
      reporter:
        description: 'Enter the name of the reporter'
        required: true

jobs:
  setup_gitrows:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        npm install gitrows
        npm install git
        
    - name: Update stock reporters
      run: |
        # check if channel is listed in channels.json
        CHANNEL_EXISTS=$(cat channels.json | jq -r 'has("'${inputs.channel}'")')
        if [ $CHANNEL_EXISTS == "true" ] ; then
           # get the base API URL for the channel
           API_URL=$(cat channels.json | jq -r '.["'${inputs.channel}'"].base_api_url')
           gitrows --api_url=$API_URL --stock_symbol=${inputs.stock_symbol} --channel=${inputs.channel} --reporter=${inputs.reporter}
        else
           echo "Error: Channel not found in channels.json"
           exit 1
        fi
